package com.example.demo.school;

import com.example.demo.school.School;
import com.example.demo.school.SchoolRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

@Component
@Order(5)
public class SchoolDataSeeder implements CommandLineRunner {

    private final SchoolRepository repository;

    public SchoolDataSeeder(SchoolRepository repository) {
        this.repository = repository;
    }

    @Override
    public void run(String... args) {
        if (repository.count() == 0) {
            java.util.List<School> list = new java.util.ArrayList<>();
            School e;
            e = new School();
            e.setSchoolId(1);
            e.setSchoolCode("FOENG");
            e.setUniversityId(2);
            e.setSchoolName("Faculty of Engineering");
            list.add(e);
            e = new School();
            e.setSchoolId(2);
            e.setSchoolCode("FOSCI");
            e.setUniversityId(2);
            e.setSchoolName("Faculty of Science");
            list.add(e);
            e = new School();
            e.setSchoolId(3);
            e.setSchoolCode("FOAGR");
            e.setUniversityId(2);
            e.setSchoolName("Faculty of Agriculture");
            list.add(e);
            e = new School();
            e.setSchoolId(4);
            e.setSchoolCode("FSNR");
            e.setUniversityId(2);
            e.setSchoolName("Faculty of Special Needs & Rehabilitation");
            list.add(e);
            e = new School();
            e.setSchoolId(5);
            e.setSchoolCode("FAH");
            e.setUniversityId(2);
            e.setSchoolName("Faculty of Arts and Humanities");
            list.add(e);
            e = new School();
            e.setSchoolId(6);
            e.setSchoolCode("FSS");
            e.setUniversityId(2);
            e.setSchoolName("Faculty of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(7);
            e.setSchoolCode("SOE");
            e.setUniversityId(2);
            e.setSchoolName("School of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(8);
            e.setSchoolCode("SAID");
            e.setUniversityId(2);
            e.setSchoolName("School of Art and Industrial Design");
            list.add(e);
            e = new School();
            e.setSchoolId(9);
            e.setSchoolCode("SOME");
            e.setUniversityId(2);
            e.setSchoolName("School of Management & Entrepreneurship");
            list.add(e);
            e = new School();
            e.setSchoolId(10);
            e.setSchoolCode("SOFBE");
            e.setUniversityId(2);
            e.setSchoolName("School of Built Environment");
            list.add(e);
            e = new School();
            e.setSchoolId(11);
            e.setSchoolCode("SCIS");
            e.setUniversityId(2);
            e.setSchoolName("School of Computing and Information Science");
            list.add(e);
            e = new School();
            e.setSchoolId(12);
            e.setSchoolCode("SOVS");
            e.setUniversityId(2);
            e.setSchoolName("School of Vocational Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(13);
            e.setSchoolCode("IDAEL");
            e.setUniversityId(2);
            e.setSchoolName("Institute of Distance Education, E-Learning & Learning Centres");
            list.add(e);
            e = new School();
            e.setSchoolId(14);
            e.setSchoolCode("DRGT");
            e.setUniversityId(2);
            e.setSchoolName("Directorate of Research & Graduate Training");
            list.add(e);
            e = new School();
            e.setSchoolId(15);
            e.setSchoolCode("SOM");
            e.setUniversityId(1);
            e.setSchoolName("School of Medicine");
            list.add(e);
            e = new School();
            e.setSchoolId(16);
            e.setSchoolCode("SOPH");
            e.setUniversityId(1);
            e.setSchoolName("School of Public Health");
            list.add(e);
            e = new School();
            e.setSchoolId(17);
            e.setSchoolCode("SOBS");
            e.setUniversityId(1);
            e.setSchoolName("School of Biomedical Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(18);
            e.setSchoolCode("SOHS");
            e.setUniversityId(1);
            e.setSchoolName("School of Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(19);
            e.setSchoolCode("SOAS");
            e.setUniversityId(1);
            e.setSchoolName("School of Agricultural Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(20);
            e.setSchoolCode("SFES");
            e.setUniversityId(1);
            e.setSchoolName("School of Forestry, Environmental and Geographical Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(21);
            e.setSchoolCode("SFTNB");
            e.setUniversityId(1);
            e.setSchoolName("School of Food Technology, Nutrition and Bio-Engineering");
            list.add(e);
            e = new School();
            e.setSchoolId(22);
            e.setSchoolCode("SOE_MAK");
            e.setUniversityId(1);
            e.setSchoolName("School of Engineering");
            list.add(e);
            e = new School();
            e.setSchoolId(23);
            e.setSchoolCode("SBE_MAK");
            e.setUniversityId(1);
            e.setSchoolName("School of Built Environment");
            list.add(e);
            e = new School();
            e.setSchoolId(24);
            e.setSchoolCode("MGIFA");
            e.setUniversityId(1);
            e.setSchoolName("Margaret Trowell School of Industrial and Fine Arts");
            list.add(e);
            e = new School();
            e.setSchoolId(25);
            e.setSchoolCode("SLPA");
            e.setUniversityId(1);
            e.setSchoolName("School of Liberal and Performing Arts");
            list.add(e);
            e = new School();
            e.setSchoolId(26);
            e.setSchoolCode("SLLC");
            e.setUniversityId(1);
            e.setSchoolName("School of Languages, Literature and Communication");
            list.add(e);
            e = new School();
            e.setSchoolId(27);
            e.setSchoolCode("SSS");
            e.setUniversityId(1);
            e.setSchoolName("School of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(28);
            e.setSchoolCode("SOP");
            e.setUniversityId(1);
            e.setSchoolName("School of Psychology");
            list.add(e);
            e = new School();
            e.setSchoolId(29);
            e.setSchoolCode("MISR");
            e.setUniversityId(1);
            e.setSchoolName("Makerere Institute of Social Research");
            list.add(e);
            e = new School();
            e.setSchoolId(30);
            e.setSchoolCode("SOECON");
            e.setUniversityId(1);
            e.setSchoolName("School of Economics");
            list.add(e);
            e = new School();
            e.setSchoolId(31);
            e.setSchoolCode("SOBUS");
            e.setUniversityId(1);
            e.setSchoolName("School of Business");
            list.add(e);
            e = new School();
            e.setSchoolId(32);
            e.setSchoolCode("SOSP");
            e.setUniversityId(1);
            e.setSchoolName("School of Statistics and Planning");
            list.add(e);
            e = new School();
            e.setSchoolId(33);
            e.setSchoolCode("SCIT");
            e.setUniversityId(1);
            e.setSchoolName("School of Computing and Informatics Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(34);
            e.setSchoolCode("EASLIS");
            e.setUniversityId(1);
            e.setSchoolName("East African School of Library and Information Science");
            list.add(e);
            e = new School();
            e.setSchoolId(35);
            e.setSchoolCode("SOE_CEES");
            e.setUniversityId(1);
            e.setSchoolName("School of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(36);
            e.setSchoolCode("SODLL");
            e.setUniversityId(1);
            e.setSchoolName("School of Distance and Lifelong Learning");
            list.add(e);
            e = new School();
            e.setSchoolId(37);
            e.setSchoolCode("SOHES");
            e.setUniversityId(1);
            e.setSchoolName("East African School of Higher Education Studies and Development");
            list.add(e);
            e = new School();
            e.setSchoolId(38);
            e.setSchoolCode("SPAS");
            e.setUniversityId(1);
            e.setSchoolName("School of Physical Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(39);
            e.setSchoolCode("SBS");
            e.setUniversityId(1);
            e.setSchoolName("School of Biological Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(40);
            e.setSchoolCode("SVR");
            e.setUniversityId(1);
            e.setSchoolName("School of Veterinary Medicine and Animal Resources");
            list.add(e);
            e = new School();
            e.setSchoolId(41);
            e.setSchoolCode("SBB");
            e.setUniversityId(1);
            e.setSchoolName("School of Biosecurity, Biotechnical and Laboratory Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(42);
            e.setSchoolCode("SOL");
            e.setUniversityId(1);
            e.setSchoolName("School of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(43);
            e.setSchoolCode("IGDS");
            e.setUniversityId(1);
            e.setSchoolName("Institute of Gender and Development Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(44);
            e.setSchoolCode("CEM_KIU");
            e.setUniversityId(3);
            e.setSchoolName("College of Economics and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(45);
            e.setSchoolCode("CHUSS_KIU");
            e.setUniversityId(3);
            e.setSchoolName("College of Humanities and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(46);
            e.setSchoolCode("CEODL_KIU");
            e.setUniversityId(3);
            e.setSchoolName("College of Education, Open and Distance Learning");
            list.add(e);
            e = new School();
            e.setSchoolId(47);
            e.setSchoolCode("SOL_KIU");
            e.setUniversityId(3);
            e.setSchoolName("School of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(48);
            e.setSchoolCode("SEAS_KIU");
            e.setUniversityId(3);
            e.setSchoolName("School of Engineering and Applied Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(49);
            e.setSchoolCode("SMC_KIU");
            e.setUniversityId(3);
            e.setSchoolName("School of Mathematics and Computing");
            list.add(e);
            e = new School();
            e.setSchoolId(50);
            e.setSchoolCode("SAHS_KIU");
            e.setUniversityId(3);
            e.setSchoolName("School of Allied Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(51);
            e.setSchoolCode("SAS_KIU");
            e.setUniversityId(3);
            e.setSchoolName("School of Agriculture Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(52);
            e.setSchoolCode("SDDEL_KIU");
            e.setUniversityId(3);
            e.setSchoolName("School of Digital, Distance and E-Learning");
            list.add(e);
            e = new School();
            e.setSchoolId(53);
            e.setSchoolCode("CMD_KIU");
            e.setUniversityId(3);
            e.setSchoolName("Faculty of Clinical Medicine and Dentistry");
            list.add(e);
            e = new School();
            e.setSchoolId(54);
            e.setSchoolCode("FBS_KIU");
            e.setUniversityId(3);
            e.setSchoolName("Faculty of Biomedical Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(55);
            e.setSchoolCode("FNS_KIU");
            e.setUniversityId(3);
            e.setSchoolName("Faculty of Nursing Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(56);
            e.setSchoolCode("FPH_KIU");
            e.setUniversityId(3);
            e.setSchoolName("Faculty of Pharmacy");
            list.add(e);
            e = new School();
            e.setSchoolId(57);
            e.setSchoolCode("FBM_KIU");
            e.setUniversityId(3);
            e.setSchoolName("Faculty of Business and Management (Western Campus)");
            list.add(e);
            e = new School();
            e.setSchoolId(58);
            e.setSchoolCode("FED_KIU");
            e.setUniversityId(3);
            e.setSchoolName("Faculty of Education (Western Campus)");
            list.add(e);
            e = new School();
            e.setSchoolId(59);
            e.setSchoolCode("ISR_KIU");
            e.setUniversityId(3);
            e.setSchoolName("Institute for Social Research");
            list.add(e);
            e = new School();
            e.setSchoolId(60);
            e.setSchoolCode("IBR_KIU");
            e.setUniversityId(3);
            e.setSchoolName("Institute of Biomedical Research");
            list.add(e);
            e = new School();
            e.setSchoolId(61);
            e.setSchoolCode("FMHS_MUST");
            e.setUniversityId(4);
            e.setSchoolName("Faculty of Medicine / Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(62);
            e.setSchoolCode("FOS_MUST");
            e.setUniversityId(4);
            e.setSchoolName("Faculty of Science");
            list.add(e);
            e = new School();
            e.setSchoolId(63);
            e.setSchoolCode("FAST_MUST");
            e.setUniversityId(4);
            e.setSchoolName("Faculty of Applied Sciences and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(64);
            e.setSchoolCode("FCI_MUST");
            e.setUniversityId(4);
            e.setSchoolName("Faculty of Computing and Informatics");
            list.add(e);
            e = new School();
            e.setSchoolId(65);
            e.setSchoolCode("FBMS_MUST");
            e.setUniversityId(4);
            e.setSchoolName("Faculty of Business and Management Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(66);
            e.setSchoolCode("FAEV_MUST");
            e.setUniversityId(4);
            e.setSchoolName("Faculty of Agriculture, Environment, and Veterinary Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(67);
            e.setSchoolCode("ITFC_MUST");
            e.setUniversityId(4);
            e.setSchoolName("Institute of Tropical Forest Conservation");
            list.add(e);
            e = new School();
            e.setSchoolId(68);
            e.setSchoolCode("FBA_UCU");
            e.setUniversityId(5);
            e.setSchoolName("Faculty of Business and Administration");
            list.add(e);
            e = new School();
            e.setSchoolId(69);
            e.setSchoolCode("FOE_UCU");
            e.setUniversityId(5);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(70);
            e.setSchoolCode("FOL_UCU");
            e.setUniversityId(5);
            e.setSchoolName("Faculty of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(71);
            e.setSchoolCode("FEDT_UCU");
            e.setUniversityId(5);
            e.setSchoolName("Faculty of Engineering, Design and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(72);
            e.setSchoolCode("SOM_UCU");
            e.setUniversityId(5);
            e.setSchoolName("School of Medicine");
            list.add(e);
            e = new School();
            e.setSchoolId(73);
            e.setSchoolCode("SOD_UCU");
            e.setUniversityId(5);
            e.setSchoolName("School of Dentistry");
            list.add(e);
            e = new School();
            e.setSchoolId(74);
            e.setSchoolCode("SSS_UCU");
            e.setUniversityId(5);
            e.setSchoolName("School of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(75);
            e.setSchoolCode("SJMC_UCU");
            e.setUniversityId(5);
            e.setSchoolName("School of Journalism, Media & Communication");
            list.add(e);
            e = new School();
            e.setSchoolId(76);
            e.setSchoolCode("BTS_UCU");
            e.setUniversityId(5);
            e.setSchoolName("Bishop Tucker School of Theology and Divinity");
            list.add(e);
            e = new School();
            e.setSchoolId(77);
            e.setSchoolCode("SCSPAG_UMI");
            e.setUniversityId(6);
            e.setSchoolName("School of Civil Service, Public Administration and Governance");
            list.add(e);
            e = new School();
            e.setSchoolId(78);
            e.setSchoolCode("SBM_UMI");
            e.setUniversityId(6);
            e.setSchoolName("School of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(79);
            e.setSchoolCode("SMS_UMI");
            e.setUniversityId(6);
            e.setSchoolName("School of Management Science");
            list.add(e);
            e = new School();
            e.setSchoolId(80);
            e.setSchoolCode("SITM_UMI");
            e.setUniversityId(6);
            e.setSchoolName("School of Infrastructure and Technology Management");
            list.add(e);
            e = new School();
            e.setSchoolId(81);
            e.setSchoolCode("FOM_GU");
            e.setUniversityId(7);
            e.setSchoolName("Faculty of Medicine");
            list.add(e);
            e = new School();
            e.setSchoolId(82);
            e.setSchoolCode("FAE_GU");
            e.setUniversityId(7);
            e.setSchoolName("Faculty of Agriculture and Environment");
            list.add(e);
            e = new School();
            e.setSchoolId(83);
            e.setSchoolCode("FOS_GU");
            e.setUniversityId(7);
            e.setSchoolName("Faculty of Science");
            list.add(e);
            e = new School();
            e.setSchoolId(84);
            e.setSchoolCode("FEH_GU");
            e.setUniversityId(7);
            e.setSchoolName("Faculty of Education and Humanities");
            list.add(e);
            e = new School();
            e.setSchoolId(85);
            e.setSchoolCode("FBDS_GU");
            e.setUniversityId(7);
            e.setSchoolName("Faculty of Business and Development Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(86);
            e.setSchoolCode("FOL_GU");
            e.setUniversityId(7);
            e.setSchoolName("Faculty of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(87);
            e.setSchoolCode("IPSS_GU");
            e.setUniversityId(7);
            e.setSchoolName("Institute of Peace and Strategic Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(88);
            e.setSchoolCode("FOM_KAB");
            e.setUniversityId(8);
            e.setSchoolName("Faculty of Medicine / School of Medicine");
            list.add(e);
            e = new School();
            e.setSchoolId(89);
            e.setSchoolCode("FETADFA_KAB");
            e.setUniversityId(8);
            e.setSchoolName("Faculty of Engineering, Technology, Applied Design and Fine Art");
            list.add(e);
            e = new School();
            e.setSchoolId(90);
            e.setSchoolCode("FOS_KAB");
            e.setUniversityId(8);
            e.setSchoolName("Faculty of Science");
            list.add(e);
            e = new School();
            e.setSchoolId(91);
            e.setSchoolCode("FCLIS_KAB");
            e.setUniversityId(8);
            e.setSchoolName("Faculty of Computing, Library and Information Science");
            list.add(e);
            e = new School();
            e.setSchoolId(92);
            e.setSchoolCode("FAES_KAB");
            e.setUniversityId(8);
            e.setSchoolName("Faculty of Agriculture and Environmental Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(93);
            e.setSchoolCode("FEMS_KAB");
            e.setUniversityId(8);
            e.setSchoolName("Faculty of Economics and Management Science");
            list.add(e);
            e = new School();
            e.setSchoolId(94);
            e.setSchoolCode("FOE_KAB");
            e.setUniversityId(8);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(95);
            e.setSchoolCode("FASS_KAB");
            e.setUniversityId(8);
            e.setSchoolName("Faculty of Arts and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(96);
            e.setSchoolCode("FET_BUS");
            e.setUniversityId(9);
            e.setSchoolName("Faculty of Engineering and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(97);
            e.setSchoolCode("FHS_BUS");
            e.setUniversityId(9);
            e.setSchoolName("Faculty of Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(98);
            e.setSchoolCode("FSE_BUS");
            e.setUniversityId(9);
            e.setSchoolName("Faculty of Science and Education");
            list.add(e);
            e = new School();
            e.setSchoolId(99);
            e.setSchoolCode("FAAS_BUS");
            e.setUniversityId(9);
            e.setSchoolName("Faculty of Agriculture and Animal Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(100);
            e.setSchoolCode("FNRES_BUS");
            e.setUniversityId(9);
            e.setSchoolName("Faculty of Natural Resources and Environmental Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(101);
            e.setSchoolCode("FMS_BUS");
            e.setUniversityId(9);
            e.setSchoolName("Faculty of Management Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(102);
            e.setSchoolCode("BAM_UMU");
            e.setUniversityId(10);
            e.setSchoolName("Faculty of Business Administration and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(103);
            e.setSchoolCode("EDU_UMU");
            e.setUniversityId(10);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(104);
            e.setSchoolCode("SCI_UMU");
            e.setUniversityId(10);
            e.setSchoolName("Faculty of Science");
            list.add(e);
            e = new School();
            e.setSchoolId(105);
            e.setSchoolCode("AGR_UMU");
            e.setUniversityId(10);
            e.setSchoolName("Faculty of Agriculture");
            list.add(e);
            e = new School();
            e.setSchoolId(106);
            e.setSchoolCode("FHS_UMU");
            e.setUniversityId(10);
            e.setSchoolName("Faculty of Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(107);
            e.setSchoolCode("FBE_UMU");
            e.setUniversityId(10);
            e.setSchoolName("Faculty of Built Environment");
            list.add(e);
            e = new School();
            e.setSchoolId(108);
            e.setSchoolCode("HSS_UMU");
            e.setUniversityId(10);
            e.setSchoolName("Faculty of Humanities and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(109);
            e.setSchoolCode("IEDS_UMU");
            e.setUniversityId(10);
            e.setSchoolName("Institute of Ethics and Development Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(110);
            e.setSchoolCode("FOL_IUIU");
            e.setUniversityId(11);
            e.setSchoolName("Faculty of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(111);
            e.setSchoolCode("FOM_IUIU");
            e.setUniversityId(11);
            e.setSchoolName("Faculty of Medicine");
            list.add(e);
            e = new School();
            e.setSchoolId(112);
            e.setSchoolCode("FOS_IUIU");
            e.setUniversityId(11);
            e.setSchoolName("Faculty of Science");
            list.add(e);
            e = new School();
            e.setSchoolId(113);
            e.setSchoolCode("FOE_IUIU");
            e.setUniversityId(11);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(114);
            e.setSchoolCode("FMS_IUIU");
            e.setUniversityId(11);
            e.setSchoolName("Faculty of Management Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(115);
            e.setSchoolCode("FASS_IUIU");
            e.setUniversityId(11);
            e.setSchoolName("Faculty of Arts and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(116);
            e.setSchoolCode("FISAL_IUIU");
            e.setUniversityId(11);
            e.setSchoolName("Faculty of Islamic Studies and Arabic Language");
            list.add(e);
            e = new School();
            e.setSchoolId(117);
            e.setSchoolCode("HMS_IUIU");
            e.setUniversityId(11);
            e.setSchoolName("Habib Medical School");
            list.add(e);
            e = new School();
            e.setSchoolId(118);
            e.setSchoolCode("ENG_NDU");
            e.setUniversityId(12);
            e.setSchoolName("Faculty of Engineering");
            list.add(e);
            e = new School();
            e.setSchoolId(119);
            e.setSchoolCode("SCI_NDU");
            e.setUniversityId(12);
            e.setSchoolName("Faculty of Science");
            list.add(e);
            e = new School();
            e.setSchoolId(120);
            e.setSchoolCode("FSS_NDU");
            e.setUniversityId(12);
            e.setSchoolName("Faculty of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(121);
            e.setSchoolCode("BAM_NDU");
            e.setUniversityId(12);
            e.setSchoolName("Faculty of Business Administration and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(122);
            e.setSchoolCode("FOE_NDU");
            e.setUniversityId(12);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(123);
            e.setSchoolCode("FEAS_NDU");
            e.setUniversityId(12);
            e.setSchoolName("Faculty of Environment and Agricultural Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(124);
            e.setSchoolCode("SCIT_ISBAT");
            e.setUniversityId(13);
            e.setSchoolName("School of Computing and Information Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(125);
            e.setSchoolCode("SBMS_ISBAT");
            e.setUniversityId(13);
            e.setSchoolName("School of Business and Management Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(126);
            e.setSchoolCode("SEAS_ISBAT");
            e.setUniversityId(13);
            e.setSchoolName("School of Engineering and Applied Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(127);
            e.setSchoolCode("FOL_CUU");
            e.setUniversityId(14);
            e.setSchoolName("Faculty of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(128);
            e.setSchoolCode("FST_CUU");
            e.setUniversityId(14);
            e.setSchoolName("Faculty of Science and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(129);
            e.setSchoolCode("FBM_CUU");
            e.setUniversityId(14);
            e.setSchoolName("Faculty of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(130);
            e.setSchoolCode("FSES_CUU");
            e.setUniversityId(14);
            e.setSchoolName("Faculty of Socio-Economic Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(131);
            e.setSchoolCode("FOE_IUEA");
            e.setUniversityId(15);
            e.setSchoolName("Faculty of Engineering");
            list.add(e);
            e = new School();
            e.setSchoolId(132);
            e.setSchoolCode("FST_IUEA");
            e.setUniversityId(15);
            e.setSchoolName("Faculty of Science and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(133);
            e.setSchoolCode("FBM_IUEA");
            e.setUniversityId(15);
            e.setSchoolName("Faculty of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(134);
            e.setSchoolCode("FOL_IUEA");
            e.setUniversityId(15);
            e.setSchoolName("Faculty of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(135);
            e.setSchoolCode("FBEPA_BSU");
            e.setUniversityId(16);
            e.setSchoolName("Faculty of Business, Economics, and Public Administration");
            list.add(e);
            e = new School();
            e.setSchoolId(136);
            e.setSchoolCode("FEAH_BSU");
            e.setUniversityId(16);
            e.setSchoolName("Faculty of Education, Arts, and Humanities");
            list.add(e);
            e = new School();
            e.setSchoolId(137);
            e.setSchoolCode("FAEST_BSU");
            e.setUniversityId(16);
            e.setSchoolName("Faculty of Agriculture, Environmental Sciences, and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(138);
            e.setSchoolCode("FHS_BSU");
            e.setUniversityId(16);
            e.setSchoolName("Faculty of Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(139);
            e.setSchoolCode("FOL_BSU");
            e.setUniversityId(16);
            e.setSchoolName("Faculty of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(140);
            e.setSchoolCode("SOB_BMU");
            e.setUniversityId(17);
            e.setSchoolName("School of Business");
            list.add(e);
            e = new School();
            e.setSchoolId(141);
            e.setSchoolCode("SOE_BMU");
            e.setUniversityId(17);
            e.setSchoolName("School of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(142);
            e.setSchoolCode("SSS_BMU");
            e.setUniversityId(17);
            e.setSchoolName("School of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(143);
            e.setSchoolCode("SST_BMU");
            e.setUniversityId(17);
            e.setSchoolName("School of Science and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(144);
            e.setSchoolCode("SHS_BMU");
            e.setUniversityId(17);
            e.setSchoolName("School of Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(145);
            e.setSchoolCode("STRS_BMU");
            e.setUniversityId(17);
            e.setSchoolName("School of Theology and Religious Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(146);
            e.setSchoolCode("SBA_NKU");
            e.setUniversityId(18);
            e.setSchoolName("School of Business Administration");
            list.add(e);
            e = new School();
            e.setSchoolId(147);
            e.setSchoolCode("SEHS_NKU");
            e.setUniversityId(18);
            e.setSchoolName("School of Education, Humanities, and Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(148);
            e.setSchoolCode("SSS_NKU");
            e.setUniversityId(18);
            e.setSchoolName("School of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(149);
            e.setSchoolCode("SOL_NKU");
            e.setUniversityId(18);
            e.setSchoolName("School of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(150);
            e.setSchoolCode("SICAD_NKU");
            e.setUniversityId(18);
            e.setSchoolName("School of Industrial, Commercial Art, and Design");
            list.add(e);
            e = new School();
            e.setSchoolId(151);
            e.setSchoolCode("SOS_NKU");
            e.setUniversityId(18);
            e.setSchoolName("School of Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(152);
            e.setSchoolCode("FBM_VU");
            e.setUniversityId(19);
            e.setSchoolName("Faculty of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(153);
            e.setSchoolCode("FST_VU");
            e.setUniversityId(19);
            e.setSchoolName("Faculty of Science and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(154);
            e.setSchoolCode("FHS_VU");
            e.setUniversityId(19);
            e.setSchoolName("Faculty of Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(155);
            e.setSchoolCode("FHSS_VU");
            e.setUniversityId(19);
            e.setSchoolName("Faculty of Humanities and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(156);
            e.setSchoolCode("SMHS_SUN");
            e.setUniversityId(20);
            e.setSchoolName("School of Medicine and Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(157);
            e.setSchoolCode("SET_SUN");
            e.setUniversityId(20);
            e.setSchoolName("School of Engineering and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(158);
            e.setSchoolCode("FOM_LIR");
            e.setUniversityId(21);
            e.setSchoolName("Faculty of Medicine");
            list.add(e);
            e = new School();
            e.setSchoolId(159);
            e.setSchoolCode("FNM_LIR");
            e.setUniversityId(21);
            e.setSchoolName("Faculty of Nursing and Midwifery");
            list.add(e);
            e = new School();
            e.setSchoolId(160);
            e.setSchoolCode("FMS_LIR");
            e.setUniversityId(21);
            e.setSchoolName("Faculty of Management Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(161);
            e.setSchoolCode("FOE_LIR");
            e.setUniversityId(21);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(162);
            e.setSchoolCode("FTS_MUN");
            e.setUniversityId(22);
            e.setSchoolName("Faculty of Technosciences");
            list.add(e);
            e = new School();
            e.setSchoolId(163);
            e.setSchoolCode("FOE_MUN");
            e.setUniversityId(22);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(164);
            e.setSchoolCode("FHS_MUN");
            e.setUniversityId(22);
            e.setSchoolName("Faculty of Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(165);
            e.setSchoolCode("FAES_MUN");
            e.setUniversityId(22);
            e.setSchoolName("Faculty of Agriculture and Environmental Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(166);
            e.setSchoolCode("FMS_MUN");
            e.setUniversityId(22);
            e.setSchoolName("Faculty of Management Science");
            list.add(e);
            e = new School();
            e.setSchoolId(167);
            e.setSchoolCode("SAS_MMU");
            e.setUniversityId(23);
            e.setSchoolName("School of Agricultural Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(168);
            e.setSchoolCode("SIC_MMU");
            e.setUniversityId(23);
            e.setSchoolName("School of Informatics and Computing");
            list.add(e);
            e = new School();
            e.setSchoolId(169);
            e.setSchoolCode("SBMS_MMU");
            e.setUniversityId(23);
            e.setSchoolName("School of Business and Management Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(170);
            e.setSchoolCode("SOE_MMU");
            e.setUniversityId(23);
            e.setSchoolName("School of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(171);
            e.setSchoolCode("SHS_MMU");
            e.setUniversityId(23);
            e.setSchoolName("School of Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(172);
            e.setSchoolCode("SHSS_MMU");
            e.setUniversityId(23);
            e.setSchoolName("School of Humanities and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(173);
            e.setSchoolCode("SNM_CIU");
            e.setUniversityId(24);
            e.setSchoolName("School of Nursing and Midwifery");
            list.add(e);
            e = new School();
            e.setSchoolId(174);
            e.setSchoolCode("SAHS_CIU");
            e.setUniversityId(24);
            e.setSchoolName("School of Allied Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(175);
            e.setSchoolCode("SBT_CIU");
            e.setUniversityId(24);
            e.setSchoolName("School of Business and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(176);
            e.setSchoolCode("FBM_SLAU");
            e.setUniversityId(25);
            e.setSchoolName("Faculty of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(177);
            e.setSchoolCode("FCSIT_SLAU");
            e.setUniversityId(25);
            e.setSchoolName("Faculty of Computer Science and Information Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(178);
            e.setSchoolCode("FOE_SLAU");
            e.setUniversityId(25);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(179);
            e.setSchoolCode("FHSS_SLAU");
            e.setUniversityId(25);
            e.setSchoolName("Faculty of Humanities and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(180);
            e.setSchoolCode("FBM_MRU");
            e.setUniversityId(26);
            e.setSchoolName("Faculty of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(181);
            e.setSchoolCode("FSTE_MRU");
            e.setUniversityId(26);
            e.setSchoolName("Faculty of Science, Technology, and Engineering");
            list.add(e);
            e = new School();
            e.setSchoolId(182);
            e.setSchoolCode("FOE_MRU");
            e.setUniversityId(26);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(183);
            e.setSchoolCode("FSSHFA_MRU");
            e.setUniversityId(26);
            e.setSchoolName("Faculty of Social Sciences, Humanities, and Fine Arts");
            list.add(e);
            e = new School();
            e.setSchoolId(184);
            e.setSchoolCode("FBSM_UNIK");
            e.setUniversityId(27);
            e.setSchoolName("Faculty of Business Studies and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(185);
            e.setSchoolCode("FOE_UNIK");
            e.setUniversityId(27);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(186);
            e.setSchoolCode("FSSP_UNIK");
            e.setUniversityId(27);
            e.setSchoolName("Faculty of Social Sciences and Psychology");
            list.add(e);
            e = new School();
            e.setSchoolId(187);
            e.setSchoolCode("FOS_UNIK");
            e.setUniversityId(27);
            e.setSchoolName("Faculty of Science");
            list.add(e);
            e = new School();
            e.setSchoolId(188);
            e.setSchoolCode("FOE_KUMU");
            e.setUniversityId(28);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(189);
            e.setSchoolCode("FST_KUMU");
            e.setUniversityId(28);
            e.setSchoolName("Faculty of Science and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(190);
            e.setSchoolCode("FSSMS_KUMU");
            e.setUniversityId(28);
            e.setSchoolName("Faculty of Social Sciences and Management Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(191);
            e.setSchoolCode("FRDA_ARU");
            e.setUniversityId(29);
            e.setSchoolName("Faculty of Rural Development and Agriculture");
            list.add(e);
            e = new School();
            e.setSchoolId(192);
            e.setSchoolCode("FBM_KU");
            e.setUniversityId(30);
            e.setSchoolName("Faculty of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(193);
            e.setSchoolCode("FCSIT_KU");
            e.setUniversityId(30);
            e.setSchoolName("Faculty of Computer Science and Information Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(194);
            e.setSchoolCode("FOE_KU");
            e.setUniversityId(30);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(195);
            e.setSchoolCode("FAD_KU");
            e.setUniversityId(30);
            e.setSchoolName("Faculty of Arts and Design");
            list.add(e);
            e = new School();
            e.setSchoolId(196);
            e.setSchoolCode("FSS_KU");
            e.setUniversityId(30);
            e.setSchoolName("Faculty of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(197);
            e.setSchoolCode("FNHS_KU");
            e.setUniversityId(30);
            e.setSchoolName("Faculty of Nursing and Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(198);
            e.setSchoolCode("FOL_UPU");
            e.setUniversityId(31);
            e.setSchoolName("Faculty of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(199);
            e.setSchoolCode("BAM_UPU");
            e.setUniversityId(31);
            e.setSchoolName("Faculty of Business Administration and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(200);
            e.setSchoolCode("FASS_UPU");
            e.setUniversityId(31);
            e.setSchoolName("Faculty of Arts and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(201);
            e.setSchoolCode("FJCS_UPU");
            e.setUniversityId(31);
            e.setSchoolName("Faculty of Journalism and Communication Studies");
            list.add(e);
            e = new School();
            e.setSchoolId(202);
            e.setSchoolCode("FASS_USHG");
            e.setUniversityId(32);
            e.setSchoolName("Faculty of Arts and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(203);
            e.setSchoolCode("FICT_USHG");
            e.setUniversityId(32);
            e.setSchoolName("Faculty of Information and Communication Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(204);
            e.setSchoolCode("SCE_UTAMU");
            e.setUniversityId(33);
            e.setSchoolName("School of Computing and Engineering");
            list.add(e);
            e = new School();
            e.setSchoolId(205);
            e.setSchoolCode("SBM_UTAMU");
            e.setUniversityId(33);
            e.setSchoolName("School of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(206);
            e.setSchoolCode("BAM_ASU");
            e.setUniversityId(34);
            e.setSchoolName("Faculty of Business Administration and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(207);
            e.setSchoolCode("FOE_ASU");
            e.setUniversityId(34);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(208);
            e.setSchoolCode("FSS_ASU");
            e.setUniversityId(34);
            e.setSchoolName("Faculty of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(209);
            e.setSchoolCode("FST_AWU");
            e.setUniversityId(35);
            e.setSchoolName("Faculty of Science and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(210);
            e.setSchoolCode("FBMS_AWU");
            e.setUniversityId(35);
            e.setSchoolName("Faculty of Business and Management Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(211);
            e.setSchoolCode("FEH_AWU");
            e.setUniversityId(35);
            e.setSchoolName("Faculty of Education and Humanities");
            list.add(e);
            e = new School();
            e.setSchoolId(212);
            e.setSchoolCode("BAM_GLRU");
            e.setUniversityId(36);
            e.setSchoolName("Faculty of Business Administration and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(213);
            e.setSchoolCode("FOE_GLRU");
            e.setUniversityId(36);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(214);
            e.setSchoolCode("FSS_GLRU");
            e.setUniversityId(36);
            e.setSchoolName("Faculty of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(215);
            e.setSchoolCode("SBM_LIU");
            e.setUniversityId(37);
            e.setSchoolName("School of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(216);
            e.setSchoolCode("SMT_LIU");
            e.setUniversityId(37);
            e.setSchoolName("School of Media and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(217);
            e.setSchoolCode("SECM_LIU");
            e.setUniversityId(37);
            e.setSchoolName("School of Education and Christian Ministry");
            list.add(e);
            e = new School();
            e.setSchoolId(218);
            e.setSchoolCode("SBM_NIU");
            e.setUniversityId(38);
            e.setSchoolName("School of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(219);
            e.setSchoolCode("STI_NIU");
            e.setUniversityId(38);
            e.setSchoolName("School of Technology and Informatics");
            list.add(e);
            e = new School();
            e.setSchoolId(220);
            e.setSchoolCode("FBA_NSU");
            e.setUniversityId(39);
            e.setSchoolName("Faculty of Business Administration");
            list.add(e);
            e = new School();
            e.setSchoolId(221);
            e.setSchoolCode("FIT_NSU");
            e.setUniversityId(39);
            e.setSchoolName("Faculty of Information Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(222);
            e.setSchoolCode("FOE_NSU");
            e.setUniversityId(39);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(223);
            e.setSchoolCode("FHSS_NSU");
            e.setUniversityId(39);
            e.setSchoolName("Faculty of Humanities and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(224);
            e.setSchoolCode("SMHS_KCU");
            e.setUniversityId(40);
            e.setSchoolName("School of Medicine and Health Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(225);
            e.setSchoolCode("SOL_KCU");
            e.setUniversityId(40);
            e.setSchoolName("School of Law");
            list.add(e);
            e = new School();
            e.setSchoolId(226);
            e.setSchoolCode("SBM_KCU");
            e.setUniversityId(40);
            e.setSchoolName("School of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(227);
            e.setSchoolCode("SCDS_KCU");
            e.setUniversityId(40);
            e.setSchoolName("School of Computing and Digital Science");
            list.add(e);
            e = new School();
            e.setSchoolId(228);
            e.setSchoolCode("SOA_KCU");
            e.setUniversityId(40);
            e.setSchoolName("School of Agriculture");
            list.add(e);
            e = new School();
            e.setSchoolId(229);
            e.setSchoolCode("FBM_SIU");
            e.setUniversityId(41);
            e.setSchoolName("Faculty of Business Management");
            list.add(e);
            e = new School();
            e.setSchoolId(230);
            e.setSchoolCode("FST_SIU");
            e.setUniversityId(41);
            e.setSchoolName("Faculty of Science and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(231);
            e.setSchoolCode("FHSS_SIU");
            e.setUniversityId(41);
            e.setSchoolName("Faculty of Humanities and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(232);
            e.setSchoolCode("FBM_IU");
            e.setUniversityId(42);
            e.setSchoolName("Faculty of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(233);
            e.setSchoolCode("FOE_IU");
            e.setUniversityId(42);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(234);
            e.setSchoolCode("FSS_IU");
            e.setUniversityId(42);
            e.setSchoolName("Faculty of Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(235);
            e.setSchoolCode("FCM_LKU");
            e.setUniversityId(43);
            e.setSchoolName("Faculty of Creative Multimedia");
            list.add(e);
            e = new School();
            e.setSchoolId(236);
            e.setSchoolCode("FICT_LKU");
            e.setUniversityId(43);
            e.setSchoolName("Faculty of Information and Communication Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(237);
            e.setSchoolCode("FDI_LKU");
            e.setUniversityId(43);
            e.setSchoolName("Faculty of Design Innovation");
            list.add(e);
            e = new School();
            e.setSchoolId(238);
            e.setSchoolCode("FBMG_LKU");
            e.setUniversityId(43);
            e.setSchoolName("Faculty of Business Management and Globalization");
            list.add(e);
            e = new School();
            e.setSchoolId(239);
            e.setSchoolCode("FBSC_ABU");
            e.setUniversityId(44);
            e.setSchoolName("Faculty of Biblical Studies and Christian Ministry");
            list.add(e);
            e = new School();
            e.setSchoolId(240);
            e.setSchoolCode("FCBA_ABU");
            e.setUniversityId(44);
            e.setSchoolName("Faculty of Communications and Business Administration");
            list.add(e);
            e = new School();
            e.setSchoolId(241);
            e.setSchoolCode("FBMS_MIU");
            e.setUniversityId(45);
            e.setSchoolName("Faculty of Business and Management Science");
            list.add(e);
            e = new School();
            e.setSchoolId(242);
            e.setSchoolCode("FEH_MIU");
            e.setUniversityId(45);
            e.setSchoolName("Faculty of Education and Humanities");
            list.add(e);
            e = new School();
            e.setSchoolId(243);
            e.setSchoolCode("FST_MIU");
            e.setUniversityId(45);
            e.setSchoolName("Faculty of Science and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(244);
            e.setSchoolCode("SEA_ROU");
            e.setUniversityId(46);
            e.setSchoolName("School of Education and Arts");
            list.add(e);
            e = new School();
            e.setSchoolId(245);
            e.setSchoolCode("SBPA_ROU");
            e.setUniversityId(46);
            e.setSchoolName("School of Business and Public Administration");
            list.add(e);
            e = new School();
            e.setSchoolId(246);
            e.setSchoolCode("SST_ROU");
            e.setUniversityId(46);
            e.setSchoolName("School of Science and Technology");
            list.add(e);
            e = new School();
            e.setSchoolId(247);
            e.setSchoolCode("SNM_AKU");
            e.setUniversityId(47);
            e.setSchoolName("School of Nursing and Midwifery");
            list.add(e);
            e = new School();
            e.setSchoolId(248);
            e.setSchoolCode("MC_AKU");
            e.setUniversityId(47);
            e.setSchoolName("Medical College");
            list.add(e);
            e = new School();
            e.setSchoolId(249);
            e.setSchoolCode("FBA_RIU");
            e.setUniversityId(48);
            e.setSchoolName("Faculty of Business Administration");
            list.add(e);
            e = new School();
            e.setSchoolId(250);
            e.setSchoolCode("FSE_RIU");
            e.setUniversityId(48);
            e.setSchoolName("Faculty of Science and Education");
            list.add(e);
            e = new School();
            e.setSchoolId(251);
            e.setSchoolCode("FAES_RIU");
            e.setUniversityId(48);
            e.setSchoolName("Faculty of Agriculture and Environmental Science");
            list.add(e);
            e = new School();
            e.setSchoolId(252);
            e.setSchoolCode("TCM_AFRU");
            e.setUniversityId(49);
            e.setSchoolName("Department of Theology and Christian Ministry");
            list.add(e);
            e = new School();
            e.setSchoolId(253);
            e.setSchoolCode("DBL_AFRU");
            e.setUniversityId(49);
            e.setSchoolName("Department of Business and Leadership");
            list.add(e);
            e = new School();
            e.setSchoolId(254);
            e.setSchoolCode("DHSS_AFRU");
            e.setUniversityId(49);
            e.setSchoolName("Department of Health and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(255);
            e.setSchoolCode("FBM_BSU");
            e.setUniversityId(50);
            e.setSchoolName("Faculty of Business and Management");
            list.add(e);
            e = new School();
            e.setSchoolId(256);
            e.setSchoolCode("FOE_BSU");
            e.setUniversityId(50);
            e.setSchoolName("Faculty of Education");
            list.add(e);
            e = new School();
            e.setSchoolId(257);
            e.setSchoolCode("FHSS_BSU");
            e.setUniversityId(50);
            e.setSchoolName("Faculty of Humanities and Social Sciences");
            list.add(e);
            e = new School();
            e.setSchoolId(258);
            e.setSchoolCode("FOA_BSU");
            e.setUniversityId(50);
            e.setSchoolName("Faculty of Agriculture");
            list.add(e);
            e = new School();
            e.setSchoolId(259);
            e.setSchoolCode("FST_BSU");
            e.setUniversityId(50);
            e.setSchoolName("Faculty of Science and Technology");
            list.add(e);
            repository.saveAll(list);
        }
    }
}
