spring.config.import=optional:dotenv:.env
server.port=8082
spring.application.name=demo

spring.security.user.name=admin
spring.security.user.password=admin123

spring.profiles.active=dev


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.h2.console.enabled=false
