package com.example.demo.department;

import com.example.demo.department.Department;
import com.example.demo.department.DepartmentRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

@Component
@Order(6)
public class DepartmentDataSeeder implements CommandLineRunner {

    private final DepartmentRepository repository;

    public DepartmentDataSeeder(DepartmentRepository repository) {
        this.repository = repository;
    }

    @Override
    public void run(String... args) {
        if (repository.count() == 0) {
            java.util.List<Department> list = new java.util.ArrayList<>();
            Department e;
            e = new Department();
            e.setDepartmentId(1);
            e.setSchoolId(1);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Civil and Environmental Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(2);
            e.setSchoolId(1);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Mechanical and Production Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(3);
            e.setSchoolId(1);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Electrical and Electronics Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(4);
            e.setSchoolId(1);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Bio-Medical and Mechatronics Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(5);
            e.setSchoolId(1);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Mining, Chemical and Petroleum Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(6);
            e.setSchoolId(2);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Biological Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(7);
            e.setSchoolId(2);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Physics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(8);
            e.setSchoolId(2);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Chemistry");
            list.add(e);
            e = new Department();
            e.setDepartmentId(9);
            e.setSchoolId(2);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Mathematics and Statistics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(10);
            e.setSchoolId(2);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Food Science Technology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(11);
            e.setSchoolId(2);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Sports Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(12);
            e.setSchoolId(3);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Agriculture Production");
            list.add(e);
            e = new Department();
            e.setDepartmentId(13);
            e.setSchoolId(3);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Soil Science and Irrigation Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(14);
            e.setSchoolId(3);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Agricultural Education and Agriculture Economics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(15);
            e.setSchoolId(3);
            e.setUniversityId(2);
            e.setDepartmentName("University Farm");
            list.add(e);
            e = new Department();
            e.setDepartmentId(16);
            e.setSchoolId(4);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Hearing Impairment and Sign Language Interpretation Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(17);
            e.setSchoolId(4);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Visual Impairment Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(18);
            e.setSchoolId(4);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Community and Disability Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(19);
            e.setSchoolId(4);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Adult, Community and Life-Long Learning");
            list.add(e);
            e = new Department();
            e.setDepartmentId(20);
            e.setSchoolId(4);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Intellectual and Development Difficulties");
            list.add(e);
            e = new Department();
            e.setDepartmentId(21);
            e.setSchoolId(5);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Languages and Communication Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(22);
            e.setSchoolId(5);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Religious Studies and Philosophy");
            list.add(e);
            e = new Department();
            e.setDepartmentId(23);
            e.setSchoolId(5);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Literature and Film Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(24);
            e.setSchoolId(5);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Performing Arts");
            list.add(e);
            e = new Department();
            e.setDepartmentId(25);
            e.setSchoolId(5);
            e.setUniversityId(2);
            e.setDepartmentName("Department of History, Archeology and Heritage");
            list.add(e);
            e = new Department();
            e.setDepartmentId(26);
            e.setSchoolId(5);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Geography");
            list.add(e);
            e = new Department();
            e.setDepartmentId(27);
            e.setSchoolId(6);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Economics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(28);
            e.setSchoolId(6);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Development Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(29);
            e.setSchoolId(6);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Political Science and Public Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(30);
            e.setSchoolId(6);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Social Work and Social Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(31);
            e.setSchoolId(6);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Sociology, Anthropology and Population Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(32);
            e.setSchoolId(6);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Psychology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(33);
            e.setSchoolId(7);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Foundations and Educational Psychology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(34);
            e.setSchoolId(7);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Technical Teacher and Instructor Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(35);
            e.setSchoolId(7);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Teacher Education and Extension");
            list.add(e);
            e = new Department();
            e.setDepartmentId(36);
            e.setSchoolId(7);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Education Planning and Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(37);
            e.setSchoolId(7);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Early Childhood and Pre-Primary Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(38);
            e.setSchoolId(7);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Curriculum, Pedagogy and Educational Media");
            list.add(e);
            e = new Department();
            e.setDepartmentId(39);
            e.setSchoolId(8);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Fine Art");
            list.add(e);
            e = new Department();
            e.setDepartmentId(40);
            e.setSchoolId(8);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Industrial and Commercial Art");
            list.add(e);
            e = new Department();
            e.setDepartmentId(41);
            e.setSchoolId(8);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Visual Communication");
            list.add(e);
            e = new Department();
            e.setDepartmentId(42);
            e.setSchoolId(9);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Finance, Accounting and Micro-finance");
            list.add(e);
            e = new Department();
            e.setDepartmentId(43);
            e.setSchoolId(9);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Management and Administrative Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(44);
            e.setSchoolId(9);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Business Administration and Entrepreneurship");
            list.add(e);
            e = new Department();
            e.setDepartmentId(45);
            e.setSchoolId(9);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Procurement and Supply Chain Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(46);
            e.setSchoolId(10);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Quantity Surveying and Property Valuation");
            list.add(e);
            e = new Department();
            e.setDepartmentId(47);
            e.setSchoolId(10);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Architecture");
            list.add(e);
            e = new Department();
            e.setDepartmentId(48);
            e.setSchoolId(10);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Geo-informatics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(49);
            e.setSchoolId(11);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Computer Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(50);
            e.setSchoolId(11);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Networks, Data Science and Artificial Intelligence");
            list.add(e);
            e = new Department();
            e.setDepartmentId(51);
            e.setSchoolId(11);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Library and Information Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(52);
            e.setSchoolId(12);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Family Life and Consumer Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(53);
            e.setSchoolId(12);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Hotel and Institutional Catering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(54);
            e.setSchoolId(12);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Cosmetology and Fashion");
            list.add(e);
            e = new Department();
            e.setDepartmentId(55);
            e.setSchoolId(12);
            e.setUniversityId(2);
            e.setDepartmentName("Department of Nutritional Science and Dietetics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(56);
            e.setSchoolId(13);
            e.setUniversityId(2);
            e.setDepartmentName("Centre for Distance Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(57);
            e.setSchoolId(13);
            e.setUniversityId(2);
            e.setDepartmentName("Centre for E-Learning");
            list.add(e);
            e = new Department();
            e.setDepartmentId(58);
            e.setSchoolId(13);
            e.setUniversityId(2);
            e.setDepartmentName("Learning Centres");
            list.add(e);
            e = new Department();
            e.setDepartmentId(59);
            e.setSchoolId(15);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Medicine");
            list.add(e);
            e = new Department();
            e.setDepartmentId(60);
            e.setSchoolId(15);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Surgery");
            list.add(e);
            e = new Department();
            e.setDepartmentId(61);
            e.setSchoolId(15);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Obstetrics and Gynaecology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(62);
            e.setSchoolId(15);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Paediatrics and Child Health");
            list.add(e);
            e = new Department();
            e.setDepartmentId(63);
            e.setSchoolId(16);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Epidemiology and Biostatistics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(64);
            e.setSchoolId(16);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Community Health and Behavioral Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(65);
            e.setSchoolId(16);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Disease Control and Environmental Health");
            list.add(e);
            e = new Department();
            e.setDepartmentId(66);
            e.setSchoolId(17);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Human Anatomy");
            list.add(e);
            e = new Department();
            e.setDepartmentId(67);
            e.setSchoolId(17);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Physiology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(68);
            e.setSchoolId(18);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Nursing");
            list.add(e);
            e = new Department();
            e.setDepartmentId(69);
            e.setSchoolId(18);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Pharmacy");
            list.add(e);
            e = new Department();
            e.setDepartmentId(70);
            e.setSchoolId(19);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Agricultural Production");
            list.add(e);
            e = new Department();
            e.setDepartmentId(71);
            e.setSchoolId(20);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Forestry, Bio-Resources and Tourism");
            list.add(e);
            e = new Department();
            e.setDepartmentId(72);
            e.setSchoolId(20);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Environmental Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(73);
            e.setSchoolId(21);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Food Technology and Human Nutrition");
            list.add(e);
            e = new Department();
            e.setDepartmentId(74);
            e.setSchoolId(22);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Civil and Environmental Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(75);
            e.setSchoolId(22);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Electrical and Computer Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(76);
            e.setSchoolId(22);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Mechanical Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(77);
            e.setSchoolId(23);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Architecture and Physical Planning");
            list.add(e);
            e = new Department();
            e.setDepartmentId(78);
            e.setSchoolId(23);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Construction Economics and Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(79);
            e.setSchoolId(24);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Fine Art");
            list.add(e);
            e = new Department();
            e.setDepartmentId(80);
            e.setSchoolId(24);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Visual Communication Design");
            list.add(e);
            e = new Department();
            e.setDepartmentId(81);
            e.setSchoolId(25);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Performing Arts and Film");
            list.add(e);
            e = new Department();
            e.setDepartmentId(82);
            e.setSchoolId(25);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Philosophy");
            list.add(e);
            e = new Department();
            e.setDepartmentId(83);
            e.setSchoolId(26);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Languages");
            list.add(e);
            e = new Department();
            e.setDepartmentId(84);
            e.setSchoolId(26);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Journalism and Communication");
            list.add(e);
            e = new Department();
            e.setDepartmentId(85);
            e.setSchoolId(27);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Sociology and Anthropology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(86);
            e.setSchoolId(27);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Political Science and Public Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(87);
            e.setSchoolId(27);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Social Work and Social Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(88);
            e.setSchoolId(28);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Mental Health and Community Psychology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(89);
            e.setSchoolId(30);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Economic Theory and Analysis");
            list.add(e);
            e = new Department();
            e.setDepartmentId(90);
            e.setSchoolId(31);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Accounting and Finance");
            list.add(e);
            e = new Department();
            e.setDepartmentId(91);
            e.setSchoolId(31);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Marketing and Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(92);
            e.setSchoolId(32);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Planning and Applied Statistics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(93);
            e.setSchoolId(33);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Computer Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(94);
            e.setSchoolId(33);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Information Technology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(95);
            e.setSchoolId(33);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Information Systems");
            list.add(e);
            e = new Department();
            e.setDepartmentId(96);
            e.setSchoolId(34);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Library and Information Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(97);
            e.setSchoolId(34);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Records and Archives Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(98);
            e.setSchoolId(35);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Humanities and Language Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(99);
            e.setSchoolId(35);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Science, Technical and Vocational Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(100);
            e.setSchoolId(36);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Adult and Community Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(101);
            e.setSchoolId(38);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Physics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(102);
            e.setSchoolId(38);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Chemistry");
            list.add(e);
            e = new Department();
            e.setDepartmentId(103);
            e.setSchoolId(38);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Mathematics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(104);
            e.setSchoolId(39);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Zoology, Entomology and Fisheries Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(105);
            e.setSchoolId(39);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Plant Sciences, Microbiology and Biotechnology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(106);
            e.setSchoolId(40);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Veterinary Clinical Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(107);
            e.setSchoolId(41);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Biosecurity, Ecosystems and Veterinary Public Health");
            list.add(e);
            e = new Department();
            e.setDepartmentId(108);
            e.setSchoolId(42);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Law and Jurisprudence");
            list.add(e);
            e = new Department();
            e.setDepartmentId(109);
            e.setSchoolId(43);
            e.setUniversityId(1);
            e.setDepartmentName("Department of Gender and Development Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(110);
            e.setSchoolId(44);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Business Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(111);
            e.setSchoolId(44);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Economics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(112);
            e.setSchoolId(44);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Finance and Accounting");
            list.add(e);
            e = new Department();
            e.setDepartmentId(113);
            e.setSchoolId(44);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Hospitality and Leisure");
            list.add(e);
            e = new Department();
            e.setDepartmentId(114);
            e.setSchoolId(45);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Applied Psychology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(115);
            e.setSchoolId(45);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Journalism and Media Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(116);
            e.setSchoolId(45);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Development, Peace, and Conflict Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(117);
            e.setSchoolId(46);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Teacher Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(118);
            e.setSchoolId(46);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Special Needs Teaching");
            list.add(e);
            e = new Department();
            e.setDepartmentId(119);
            e.setSchoolId(47);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Public and Private Law");
            list.add(e);
            e = new Department();
            e.setDepartmentId(120);
            e.setSchoolId(48);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Civil Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(121);
            e.setSchoolId(48);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Electrical Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(122);
            e.setSchoolId(48);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Mechanical Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(123);
            e.setSchoolId(49);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Computer Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(124);
            e.setSchoolId(49);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Information Technology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(125);
            e.setSchoolId(50);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Medical Laboratory Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(126);
            e.setSchoolId(51);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Agricultural Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(127);
            e.setSchoolId(52);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Digital and Distance Learning");
            list.add(e);
            e = new Department();
            e.setDepartmentId(128);
            e.setSchoolId(53);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Clinical Medicine");
            list.add(e);
            e = new Department();
            e.setDepartmentId(129);
            e.setSchoolId(53);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Dentistry");
            list.add(e);
            e = new Department();
            e.setDepartmentId(130);
            e.setSchoolId(54);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Anatomy");
            list.add(e);
            e = new Department();
            e.setDepartmentId(131);
            e.setSchoolId(54);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Physiology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(132);
            e.setSchoolId(54);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Biochemistry");
            list.add(e);
            e = new Department();
            e.setDepartmentId(133);
            e.setSchoolId(54);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Microbiology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(134);
            e.setSchoolId(55);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Nursing Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(135);
            e.setSchoolId(56);
            e.setUniversityId(3);
            e.setDepartmentName("Department of Pharmacy");
            list.add(e);
            e = new Department();
            e.setDepartmentId(136);
            e.setSchoolId(61);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Medicine");
            list.add(e);
            e = new Department();
            e.setDepartmentId(137);
            e.setSchoolId(61);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Nursing");
            list.add(e);
            e = new Department();
            e.setDepartmentId(138);
            e.setSchoolId(61);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Pharmacy");
            list.add(e);
            e = new Department();
            e.setDepartmentId(139);
            e.setSchoolId(62);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Biological Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(140);
            e.setSchoolId(62);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Chemistry");
            list.add(e);
            e = new Department();
            e.setDepartmentId(141);
            e.setSchoolId(62);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Physics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(142);
            e.setSchoolId(62);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Mathematics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(143);
            e.setSchoolId(63);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Biomedical Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(144);
            e.setSchoolId(64);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Computer Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(145);
            e.setSchoolId(64);
            e.setUniversityId(4);
            e.setDepartmentName("Department of Information Technology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(146);
            e.setSchoolId(68);
            e.setUniversityId(5);
            e.setDepartmentName("Department of Business Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(147);
            e.setSchoolId(69);
            e.setUniversityId(5);
            e.setDepartmentName("Department of Education Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(148);
            e.setSchoolId(70);
            e.setUniversityId(5);
            e.setDepartmentName("Department of Private and Property Law");
            list.add(e);
            e = new Department();
            e.setDepartmentId(149);
            e.setSchoolId(71);
            e.setUniversityId(5);
            e.setDepartmentName("Department of Civil and Building Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(150);
            e.setSchoolId(72);
            e.setUniversityId(5);
            e.setDepartmentName("Department of Medicine");
            list.add(e);
            e = new Department();
            e.setDepartmentId(151);
            e.setSchoolId(73);
            e.setUniversityId(5);
            e.setDepartmentName("Department of Dentistry");
            list.add(e);
            e = new Department();
            e.setDepartmentId(152);
            e.setSchoolId(74);
            e.setUniversityId(5);
            e.setDepartmentName("Department of Social Work");
            list.add(e);
            e = new Department();
            e.setDepartmentId(153);
            e.setSchoolId(75);
            e.setUniversityId(5);
            e.setDepartmentName("Department of Journalism and Mass Communication");
            list.add(e);
            e = new Department();
            e.setDepartmentId(154);
            e.setSchoolId(81);
            e.setUniversityId(7);
            e.setDepartmentName("Department of Clinical Medicine");
            list.add(e);
            e = new Department();
            e.setDepartmentId(155);
            e.setSchoolId(82);
            e.setUniversityId(7);
            e.setDepartmentName("Department of Agriculture");
            list.add(e);
            e = new Department();
            e.setDepartmentId(156);
            e.setSchoolId(83);
            e.setUniversityId(7);
            e.setDepartmentName("Department of Physical Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(157);
            e.setSchoolId(84);
            e.setUniversityId(7);
            e.setDepartmentName("Department of Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(158);
            e.setSchoolId(85);
            e.setUniversityId(7);
            e.setDepartmentName("Department of Business Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(159);
            e.setSchoolId(86);
            e.setUniversityId(7);
            e.setDepartmentName("Department of Law");
            list.add(e);
            e = new Department();
            e.setDepartmentId(160);
            e.setSchoolId(96);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Computer Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(161);
            e.setSchoolId(96);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Agricultural Mechanization");
            list.add(e);
            e = new Department();
            e.setDepartmentId(162);
            e.setSchoolId(97);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Medicine and Community Health");
            list.add(e);
            e = new Department();
            e.setDepartmentId(163);
            e.setSchoolId(98);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Science Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(164);
            e.setSchoolId(99);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Animal Production");
            list.add(e);
            e = new Department();
            e.setDepartmentId(165);
            e.setSchoolId(100);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Natural Resource Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(166);
            e.setSchoolId(101);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Management Studies");
            list.add(e);
            e = new Department();
            e.setDepartmentId(167);
            e.setSchoolId(102);
            e.setUniversityId(10);
            e.setDepartmentName("Department of Business Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(168);
            e.setSchoolId(103);
            e.setUniversityId(10);
            e.setDepartmentName("Department of Educational Foundations");
            list.add(e);
            e = new Department();
            e.setDepartmentId(169);
            e.setSchoolId(104);
            e.setUniversityId(10);
            e.setDepartmentName("Department of Biological Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(170);
            e.setSchoolId(110);
            e.setUniversityId(11);
            e.setDepartmentName("Department of Public Law");
            list.add(e);
            e = new Department();
            e.setDepartmentId(171);
            e.setSchoolId(111);
            e.setUniversityId(11);
            e.setDepartmentName("Department of Medicine");
            list.add(e);
            e = new Department();
            e.setDepartmentId(172);
            e.setSchoolId(112);
            e.setUniversityId(11);
            e.setDepartmentName("Department of Computer Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(173);
            e.setSchoolId(116);
            e.setUniversityId(11);
            e.setDepartmentName("Department of Arabic Language");
            list.add(e);
            e = new Department();
            e.setDepartmentId(174);
            e.setSchoolId(124);
            e.setUniversityId(13);
            e.setDepartmentName("Department of Information Technology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(175);
            e.setSchoolId(125);
            e.setUniversityId(13);
            e.setDepartmentName("Department of Business Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(176);
            e.setSchoolId(126);
            e.setUniversityId(13);
            e.setDepartmentName("Department of Applied Electronics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(177);
            e.setSchoolId(146);
            e.setUniversityId(18);
            e.setDepartmentName("Department of Business Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(178);
            e.setSchoolId(147);
            e.setUniversityId(18);
            e.setDepartmentName("Department of Humanities");
            list.add(e);
            e = new Department();
            e.setDepartmentId(179);
            e.setSchoolId(150);
            e.setUniversityId(18);
            e.setDepartmentName("Department of Commercial Art and Design");
            list.add(e);
            e = new Department();
            e.setDepartmentId(180);
            e.setSchoolId(156);
            e.setUniversityId(20);
            e.setDepartmentName("Department of Health Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(181);
            e.setSchoolId(157);
            e.setUniversityId(20);
            e.setDepartmentName("Department of Electronics and Computer Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(182);
            e.setSchoolId(162);
            e.setUniversityId(22);
            e.setDepartmentName("Department of Information Technology");
            list.add(e);
            e = new Department();
            e.setDepartmentId(183);
            e.setSchoolId(163);
            e.setUniversityId(22);
            e.setDepartmentName("Department of Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(184);
            e.setSchoolId(204);
            e.setUniversityId(33);
            e.setDepartmentName("Department of Computer Science and Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(185);
            e.setSchoolId(205);
            e.setUniversityId(33);
            e.setDepartmentName("Department of Business Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(186);
            e.setSchoolId(224);
            e.setUniversityId(40);
            e.setDepartmentName("Department of Medicine and Surgery");
            list.add(e);
            e = new Department();
            e.setDepartmentId(187);
            e.setSchoolId(225);
            e.setUniversityId(40);
            e.setDepartmentName("Department of Law");
            list.add(e);
            e = new Department();
            e.setDepartmentId(188);
            e.setSchoolId(227);
            e.setUniversityId(40);
            e.setDepartmentName("Department of Digital Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(189);
            e.setSchoolId(235);
            e.setUniversityId(43);
            e.setDepartmentName("Department of Multimedia Design");
            list.add(e);
            e = new Department();
            e.setDepartmentId(190);
            e.setSchoolId(236);
            e.setUniversityId(43);
            e.setDepartmentName("Department of Software Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(191);
            e.setSchoolId(237);
            e.setUniversityId(43);
            e.setDepartmentName("Department of Fashion and Design");
            list.add(e);
            e = new Department();
            e.setDepartmentId(192);
            e.setSchoolId(247);
            e.setUniversityId(47);
            e.setDepartmentName("Department of Nursing Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(193);
            e.setSchoolId(248);
            e.setUniversityId(47);
            e.setDepartmentName("Department of Clinical Medicine");
            list.add(e);
            e = new Department();
            e.setDepartmentId(194);
            e.setSchoolId(255);
            e.setUniversityId(50);
            e.setDepartmentName("Department of Business Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(195);
            e.setSchoolId(256);
            e.setUniversityId(50);
            e.setDepartmentName("Department of Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(196);
            e.setSchoolId(259);
            e.setUniversityId(50);
            e.setDepartmentName("Department of Computer Science");
            list.add(e);
            e = new Department();
            e.setDepartmentId(207);
            e.setSchoolId(112);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Computer Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(208);
            e.setSchoolId(112);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Agricultural & Water Resources Engineering");
            list.add(e);
            e = new Department();
            e.setDepartmentId(209);
            e.setSchoolId(113);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Nursing & Public Health");
            list.add(e);
            e = new Department();
            e.setDepartmentId(210);
            e.setSchoolId(114);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Science Education");
            list.add(e);
            e = new Department();
            e.setDepartmentId(211);
            e.setSchoolId(115);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Natural Resource Economics");
            list.add(e);
            e = new Department();
            e.setDepartmentId(212);
            e.setSchoolId(116);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Animal Production & Management");
            list.add(e);
            e = new Department();
            e.setDepartmentId(213);
            e.setSchoolId(117);
            e.setUniversityId(9);
            e.setDepartmentName("Department of Business Administration");
            list.add(e);
            e = new Department();
            e.setDepartmentId(214);
            e.setSchoolId(118);
            e.setUniversityId(20);
            e.setDepartmentName("Department of Medicine and Surgery");
            list.add(e);
            e = new Department();
            e.setDepartmentId(215);
            e.setSchoolId(118);
            e.setUniversityId(20);
            e.setDepartmentName("Department of Nursing Sciences");
            list.add(e);
            e = new Department();
            e.setDepartmentId(216);
            e.setSchoolId(119);
            e.setUniversityId(20);
            e.setDepartmentName("Department of Electronics and Computer Engineering");
            list.add(e);
            repository.saveAll(list);
        }
    }
}
